# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u0jWF2OH3m0T5JWL4DZYjN2eP_KUhwr_
"""

import gradio as gr
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Simulate some house price data
np.random.seed(0)
num_samples = 200
rooms = np.random.randint(1, 6, size=num_samples)  # Number of rooms
sqft = np.random.randint(500, 3000, size=num_samples)  # Square footage
age = np.random.randint(0, 100, size=num_samples)  # Age of the house

# Price calculation (with noise)
price = 50_000 + (rooms * 20_000) + (sqft * 50) - (age * 300) + np.random.randn(num_samples) * 5000

# Create a DataFrame
data = pd.DataFrame({
    'rooms': rooms,
    'sqft': sqft,
    'age': age,
    'price': price
})

# Split data into features (X) and target (y)
X = data[['rooms', 'sqft', 'age']]
y = data['price']

# Split into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a linear regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Normalize data using StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Function to predict house price based on user input
def predict_price(rooms, sqft, age):
    features = np.array([[rooms, sqft, age]])
    features_scaled = scaler.transform(features)
    prediction = model.predict(features_scaled)
    return f"Predicted House Price: ${prediction[0]:,.2f}"

# Create Gradio interface
interface = gr.Interface(
    fn=predict_price,
    inputs=[
        gr.Slider(minimum=1, maximum=6, step=1, label="Number of Rooms"),
        gr.Slider(minimum=500, maximum=3000, step=100, label="Square Footage"),
        gr.Slider(minimum=0, maximum=100, step=1, label="Age of the House")
    ],
    outputs="text",
    live=True,
    title="House Price Prediction",
    description="Predict the price of a house based on the number of rooms, square footage, and the age of the house."
)

# Launch the interface
interface.launch()